services:
  web:
    image: ${DOCKERHUB_USERNAME}/flask-app:v1 
    ports:
      - "80:80"    
         #ec2 host port:container port means EC2 port 80 --> Container port 80 --> Gunicorn port 80 --> Flask application