name: Deploy Flask App

on:
  workflow_run:
    workflows: ["Docker Build & Push"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'

    runs-on: self-hosted

    env:
      DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v2

      - name: Debug Compose
        run: |
          echo "DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME"
          cat docker-compose.yml
          docker compose config

      - name: Deploy
        run: |
          docker compose down
          docker compose pull
          docker compose up -d --force-recreate

      - name: Check containers
        run: docker compose ps

      - name: Check logs
        run: docker compose logs --tail=100